[project]
    name = "glance_run"
    version = "1.0.0"
    description = "Add your description here"
    readme = "README.md"
    requires-python = ">=3.13"
    dependencies = [
        "dotenv>=0.9.9",
        "paul-tools>=1.0.7",
    ]
